### ISSUE TITLE
void WT2003S::pause( void) with return.... 

### ISSUE THREAD

**Issue by philteta** [sparkfun/SparkFun_WT2003S_MP3_Decoder_Arduino_Library#3]
### Subject of the issue
ESP32 compatibility

### Your workbench
* M5 Stack Atome (ESP32 based)
* Software serial
* USB
* I have the solution....

### Steps to reproduce
Try to compile this lib in arduino

### Expected behaviour
Compliation ok

### Actual behaviour
Error while compliling

Solution 

In SparkFun_WT2003S_MP3_Decoder.cpp

void 		WT2003S::pause( void )
{
	commandBytes[0] = MP3_COMMAND_PAUSE;
	sendCommand(1);
	return (getResponse());
}

and in SparkFun_WT2003S_MP3_Decoder.h

void pause( void );

I m not a great programmer (and not a programmer at all) but I do not understand how a void function can have a return...

Basiclly I change by that  
uint8_t  WT2003S::pause( void )
{
	commandBytes[0] = MP3_COMMAND_PAUSE;
	sendCommand(1);
	return (getResponse());
}
and

uint8_t pause( void );

and it works :)

**Comment by nseidle** [comment]
Thanks for reporting! Should be fixed in latest release.
